#!/usr/bin/env bash
# =============================================================================
# Seed _assets/ with RANDOM placeholder clips from the source collection.
# 用随机视频填充 _assets/ 作为占位，方便先把页面搭起来。之后你换成自己挑的即可。
#
# 用法 / Usage:
#   SRC_ROOT=/path/to/seer_videos_collection ./scripts/seed_random.sh
#   (不传 SRC_ROOT 就用下面的默认路径)
#
# 它会:
#   - 从 12B_720P 的 FA3/sparse 配对里随机挑 N_CMP 组 -> _assets/comparisons/
#   - 从 12B_720P sparse 里随机挑 N_GAL 个      -> _assets/gallery/
# 不会改动/删除源文件，只是复制。
# =============================================================================
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC_ROOT="${SRC_ROOT:-/Users/bytedance/Downloads/seer_videos_collection}"
N_CMP="${N_CMP:-4}"
N_GAL="${N_GAL:-8}"
SEED="${SEED:-7}"   # 固定随机种子, 结果可复现

ASSETS="$ROOT/_assets"
mkdir -p "$ASSETS/comparisons" "$ASSETS/gallery"

# deterministic shuffle helper (seeded)
sh() { awk 'BEGIN{srand('"$SEED"')} {print rand()"\t"$0}' | sort -k1,1 | cut -f2-; }

# paired comparison source: 12B_720P, categories with both FA3 and sparse
declare -a CATS=("animal" "motion_bench")
echo "==> Seeding $N_CMP comparison pairs from 12B_720P"
i=1
# build a pool of "category/filename" that exist in both FA3 and sparse
POOL="$(for c in "${CATS[@]}"; do
  fa="$SRC_ROOT/12B_720P/FA3/$c/videos"; sp="$SRC_ROOT/12B_720P/sparse/$c/videos"
  [ -d "$fa" ] && [ -d "$sp" ] || continue
  for f in "$sp"/*.mp4; do b="$(basename "$f")"; [ -f "$fa/$b" ] && echo "$c|$b"; done
done | sh | head -n "$N_CMP")"

while IFS='|' read -r c b; do
  [ -z "${c:-}" ] && continue
  nm="$(printf '%02d_%s' "$i" "$(echo "$b" | sed 's/\.mp4$//; s/[^A-Za-z0-9]/_/g')")"
  d="$ASSETS/comparisons/$nm"; mkdir -p "$d"
  cp "$SRC_ROOT/12B_720P/FA3/$c/videos/$b"    "$d/full.mp4"
  cp "$SRC_ROOT/12B_720P/sparse/$c/videos/$b" "$d/veda.mp4"
  printf 'Waver-T2V-12B  ·  720P · 241 frames\n95%% sparsity vs. Full Attention\n' > "$d/label.txt"
  echo "   + $nm  ($c/$b)"
  i=$((i+1))
done <<< "$POOL"

echo "==> Seeding $N_GAL gallery clips from 12B_720P/sparse"
GPOOL="$(for c in "${CATS[@]}"; do
  sp="$SRC_ROOT/12B_720P/sparse/$c/videos"; [ -d "$sp" ] || continue
  for f in "$sp"/*.mp4; do echo "$c|$(basename "$f")"; done
done | sh | head -n "$N_GAL")"
j=1
while IFS='|' read -r c b; do
  [ -z "${c:-}" ] && continue
  nm="$(printf '%02d_%s' "$j" "$(echo "$b" | sed 's/\.mp4$//; s/[^A-Za-z0-9]/_/g')")"
  cp "$SRC_ROOT/12B_720P/sparse/$c/videos/$b" "$ASSETS/gallery/$nm.mp4"
  echo "Generated by Veda · Waver-T2V-12B · 720P · 95% sparsity" > "$ASSETS/gallery/$nm.txt"
  echo "   + $nm  ($c/$b)"
  j=$((j+1))
done <<< "$GPOOL"

echo "==> Seeded. Now run: ./scripts/process_media.sh"
